import pytest
from luis_wrapper import LuisResponse



def test_Given_EssentialParametersAreMissing_When_InitializingClass_Then_ExceptionIsRaised():
    assert False

def test_Given_NoEssentialParametersAreMissing_When_InitializingClass_Then_ClassIsInitializedCorrectly():
    assert False

def test_Given_NonEssentialParametersAreMissing_When_InitializingClass_Then_ClassIsInitializedCorrectlyWithMissingAttributesSetToNone():
    assert False

def test_Given_AllParametersAreGiven_When_InitializingClass_Then_ClassIsInitializedCorrectlyWithoutAnyNoneValues():
    assert False